name: "gha1"

on:
  push:
    branches: [master, main]
    paths-ignore:
      - "**.md"
  pull_request:
    branches: "**"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "This job will always succeed!"
          echo "Success: $(date)"

  failure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Failure step
        run: |
          echo "This job will always fail!"
          echo "Failure: $(date)"
          exit 1
