name: GHA1 - Simple Test Workflow

on:
  push:
    branches: [master, main]
  pull_request:
    branches: "**"
  workflow_dispatch:

jobs:
  success-job:
    runs-on: ubuntu-latest
    name: Always Success Job
    steps:
      - name: Success step
        run: |
          echo "This job will always succeed!"
          echo "Success: $(date)"

  failure-job:
    runs-on: ubuntu-latest
    name: Always Failure Job
    steps:
      - name: Failure step
        run: |
          echo "This job will always fail!"
          echo "Failure: $(date)"
          exit 1
