name: "gha2"

on:
  push:
    branches: [master, main]
    paths-ignore:
      - "**"
      - "!**.md"
  pull_request:
    branches: "**"
    paths-ignore:
      - "**"
      - "!**.md"
  workflow_dispatch:

jobs:
  success-job:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "This job will always succeed!"
          echo "Success: $(date)"
